# Welcome to Jekyll!

title: stone-zeng.github.io
lang: en-US  # For correct hyphenation, we need set the language to en-US.
baseurl: ""
url: https://thedaimon.cn
copyright: © 2022 Liu Kang
github_username: stone-zeng

incremental: true
permalink: :year-:month-:day-:title/
exclude:
  - .eslintrc.json
  - .gitattributes
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - package.json
  - README.md
  - _draft/
  - .vscode/
  - node_modules/
  - src/
  - temp/
  - vendor/

markdown: kramdown

theme: minima
minima:
  social_links:
    email: xdzeng96@gmail.com
    github: stone-zeng
    twitter: xiangdong_zeng
    telegram: xdzeng96
    rss: rss
plugins:
  - jekyll-feed
  - jekyll-paginate
sass:
    style: compressed
paginate: 10
paginate_path: /page/:num

