# Welcome to Jekyll!

title: stone-zeng.github.io
lang: en-US  # For correct hyphenation, we need set the language to en-US.
baseurl: ""
url: https://stone-zeng.github.io/
google_analytics: UA-132846370-1
copyright: © 2018–2019 Xiangdong Zeng
github_username: stone-zeng

incremental: true
permalink: :year-:month-:day-:title/
exclude:
  - _draft/
  - .eslintrc.json
  - .gitattributes
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - package.json
  - README.md
  - src/
  - temp/
  - vendor/

markdown: kramdown

theme: minima
minima:
  social_links:
    email: xdzeng96@gmail.com
    github: stone-zeng
    stackexchange: 136923/stone-zeng
    telegram: xdzeng96
    rss: rss
plugins:
  - jekyll-feed
sass:
    style: compressed
